name: temple_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
# Remove or change this line if you want to publish your package.
publish_to: "none"

# Application version and build number.
# Format: major.minor.patch+build
# Example: 1.0.0+1
version: 1.0.0+1

environment:
  # Specify the Dart SDK version constraints.
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  http: ^1.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  shimmer: ^3.0.0
  dropdown_button2: ^2.3.9
  table_calendar: ^3.2.0
  audioplayers: ^6.1.0
  just_audio: ^0.10.5
  firebase_crashlytics: ^5.0.1
  firebase_analytics: ^12.0.1
  firebase_core: ^4.1.0
  firebase_auth: ^6.1.0
  flutter_svg: ^2.2.1
  # firebase_app_check: ^0.4.1
  firebase_messaging: 16.0.2
  flutter_local_notifications: ^17.2.3
  # ------------------------
  # UI & Design
  # ------------------------

  fluttertoast: ^8.2.14 # Toast notifications

  # ------------------------
  # State Management
  # Firebase Analytics

dev_dependencies:
  flutter_test:
    sdk: flutter

  # ------------------------
  # Development & Code Quality
  # ------------------------
  flutter_lints: ^5.0.0 # Recommended lint rules
  build_runner: # Code generation utility
  hive_generator: # Hive type adapters generator

flutter:
  uses-material-design: true

  assets:
    # Pick one strategy: either list individual files OR include folders

    # If you want to include whole folders (simpler, less duplication):
    - assets/
    - assets/loginUi.jpg
    - assets/icons/
    - assets/bottomNavBar/
    - assets/svg/

  fonts:
    - family: NotoSansMalayalam
      fonts:
        - asset: assets/fonts/NotoSansMalayalam-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansMalayalam-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansMalayalam-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansMalayalam-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
