name: temple
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
# Remove or change this line if you want to publish your package.
publish_to: "none"  

# Application version and build number.
# Format: major.minor.patch+build
# Example: 1.0.0+1
version: 1.0.0+1

environment:
  # Specify the Dart SDK version constraints.
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # ------------------------
  # UI & Design
  # ------------------------
  cupertino_icons: ^1.0.8         # iOS-style icons
  flutter_screenutil: ^5.9.3      # Responsive UI design
  shimmer: ^3.0.0                 # Shimmer effect for loading states
  dropdown_button2: ^2.3.9        # Advanced dropdown widget
  table_calendar: ^3.2.0          # Calendar widget
  flutter_svg:                    # SVG rendering

  # ------------------------
  # State Management
  # ------------------------
  flutter_riverpod: ^2.6.1        # State management

  # ------------------------
  # Networking & APIs
  # ------------------------
  http: ^1.5.0                    # HTTP requests

  # ------------------------
  # Database & Local Storage
  # ------------------------
  hive: ^2.2.3                    # Lightweight local database
  hive_flutter: ^1.1.0            # Hive bindings for Flutter
  path_provider: ^2.1.2           # Path access for local storage

  # ------------------------
  # Audio & Media
  # ------------------------
  audioplayers: ^6.1.0            # Audio playback
  just_audio: ^0.10.5             # Advanced audio playback

  # ------------------------
  # Firebase & Analytics
  # ------------------------
  firebase_core: ^4.1.0           # Core Firebase SDK
  firebase_crashlytics: ^5.0.1    # Firebase Crashlytics for error reporting
  firebase_analytics: ^12.0.1     # Firebase Analytics

dev_dependencies:
  flutter_test:
    sdk: flutter

  # ------------------------
  # Development & Code Quality
  # ------------------------
  flutter_lints: ^5.0.0           # Recommended lint rules
  build_runner:                   # Code generation utility
  hive_generator:                 # Hive type adapters generator

flutter:
  # Ensure Material icons are included in the project.
  uses-material-design: true

  # ------------------------
  # Assets (images, icons, backgrounds, etc.)
  # ------------------------
  assets:
    - assets/
    - assets/icons/
    - assets/bottomNavBar/
    - assets/svg/
    - assets/svg/thumbnailimage.svg

  # ------------------------
  # Custom Fonts
  # ------------------------
  fonts:
    - family: NotoSansMalayalam
      fonts:
        - asset: assets/fonts/NotoSansMalayalam-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansMalayalam-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansMalayalam-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansMalayalam-Bold.ttf
          weight: 700
