name: temple
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
# Remove or change this line if you want to publish your package.
publish_to: "none"

# Application version and build number.
# Format: major.minor.patch+build
# Example: 1.0.0+1
version: 1.0.0+1

environment:
  # Specify the Dart SDK version constraints.
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  http: ^1.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  shimmer: ^3.0.0
  dropdown_button2: ^2.3.9
  table_calendar: ^3.2.0
  audioplayers: ^6.1.0
  just_audio: ^0.10.5
  firebase_crashlytics: ^5.0.1
  firebase_analytics: ^12.0.1
  firebase_core: ^4.1.0
  flutter_svg: ^2.2.1
  # ------------------------
  # UI & Design
  # ------------------------

  fluttertoast: ^8.2.14 # Toast notifications

  # ------------------------
  # State Management
  # Firebase Analytics

dev_dependencies:
  flutter_test:
    sdk: flutter

  # ------------------------
  # Development & Code Quality
  # ------------------------
  flutter_lints: ^5.0.0 # Recommended lint rules
  build_runner: # Code generation utility
  hive_generator: # Hive type adapters generator

flutter:
  # Ensure Material icons are included in the project.
  uses-material-design: true

  # ------------------------
  # Assets (images, icons, backgrounds, etc.)
  # ------------------------
  assets:
    - assets/icons/play.png
    - assets/icons/pause.png
    - assets/icons/next.png
    - assets/icons/back.png

    - assets/menu.png
    - assets/bell.png
    - assets/background.jpg
    - assets/bottomNavBar/bn1.png
    - assets/bottomNavBar/bn2.png
    - assets/bottomNavBar/bn3.png
    - assets/bottomNavBar/bn4.png
    - assets/bottomNavBar/bn5.png
    - assets/backIcon.png
    - assets/calendar.png
    - assets/icons/menu.png
    - assets/icons/bell.png
    - assets/icons/sound.png
    - assets/icons/mute.png
    - assets/fallBack.png
    - assets/icons/playlist.png
    - assets/loginUI.jpg
    - assets/icons/facebook.png
    - assets/icons/google.png

    # To add assets to your application, add an assets section, like this:
    # assets:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/to/resolution-aware-images

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/to/asset-from-package

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    - assets/
    - assets/icons/
    - assets/bottomNavBar/
    - assets/svg/
    - assets/svg/thumbnailimage.svg

  # ------------------------
  # Custom Fonts
  # ------------------------
  fonts:
    - family: NotoSansMalayalam
      fonts:
        - asset: assets/fonts/NotoSansMalayalam-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansMalayalam-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansMalayalam-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansMalayalam-Bold.ttf
          weight: 700
