// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs3a1OCrtUx8C_6ja3vzswjBQPTZwFmjc',
    appId: '1:799670961061:web:878ef8c37cb9ea789bde4c',
    messagingSenderId: '799670961061',
    projectId: 'temple-project-2d223',
    authDomain: 'temple-project-2d223.firebaseapp.com',
    storageBucket: 'temple-project-2d223.firebasestorage.app',
    measurementId: 'G-0ZSRHP2Y14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1stOtrM-IPce0MOl3RHR6U5UxaxWmBkk',
    appId: '1:799670961061:android:20b987eb993677209bde4c',
    messagingSenderId: '799670961061',
    projectId: 'temple-project-2d223',
    storageBucket: 'temple-project-2d223.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA26ZtYBQuI85WchwiwH2ixBmHnA4oepCQ',
    appId: '1:799670961061:ios:d150bffda859d0259bde4c',
    messagingSenderId: '799670961061',
    projectId: 'temple-project-2d223',
    storageBucket: 'temple-project-2d223.firebasestorage.app',
    androidClientId: '799670961061-0emuo3s98iiq4c2thkcb0gel16ppe6bs.apps.googleusercontent.com',
    iosClientId: '799670961061-8ekvg5ophtubg4fh49lq17f8mbc9i0bc.apps.googleusercontent.com',
    iosBundleId: 'com.example.temple.in',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA26ZtYBQuI85WchwiwH2ixBmHnA4oepCQ',
    appId: '1:799670961061:ios:d150bffda859d0259bde4c',
    messagingSenderId: '799670961061',
    projectId: 'temple-project-2d223',
    storageBucket: 'temple-project-2d223.firebasestorage.app',
    androidClientId: '799670961061-0emuo3s98iiq4c2thkcb0gel16ppe6bs.apps.googleusercontent.com',
    iosClientId: '799670961061-8ekvg5ophtubg4fh49lq17f8mbc9i0bc.apps.googleusercontent.com',
    iosBundleId: 'com.example.temple.in',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs3a1OCrtUx8C_6ja3vzswjBQPTZwFmjc',
    appId: '1:799670961061:web:5b15ab83ef8094ef9bde4c',
    messagingSenderId: '799670961061',
    projectId: 'temple-project-2d223',
    authDomain: 'temple-project-2d223.firebaseapp.com',
    storageBucket: 'temple-project-2d223.firebasestorage.app',
    measurementId: 'G-FFGQ3RJ8MR',
  );
}
