// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs3a1OCrtUx8C_6ja3vzswjBQPTZwFmjc',
    appId: '1:799670961061:web:80834b77694f26e79bde4c',
    messagingSenderId: '799670961061',
    projectId: 'temple-project-2d223',
    authDomain: 'temple-project-2d223.firebaseapp.com',
    storageBucket: 'temple-project-2d223.firebasestorage.app',
    measurementId: 'G-TDRSDVSBWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1stOtrM-IPce0MOl3RHR6U5UxaxWmBkk',
    appId: '1:799670961061:android:97845653ee75efdf9bde4c',
    messagingSenderId: '799670961061',
    projectId: 'temple-project-2d223',
    storageBucket: 'temple-project-2d223.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA26ZtYBQuI85WchwiwH2ixBmHnA4oepCQ',
    appId: '1:799670961061:ios:b64a82971f4aa50e9bde4c',
    messagingSenderId: '799670961061',
    projectId: 'temple-project-2d223',
    storageBucket: 'temple-project-2d223.firebasestorage.app',
    iosClientId: '799670961061-dbgulcqjfpn6r4h33a2vumne6jafnbhu.apps.googleusercontent.com',
    iosBundleId: 'com.example.temple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA26ZtYBQuI85WchwiwH2ixBmHnA4oepCQ',
    appId: '1:799670961061:ios:b64a82971f4aa50e9bde4c',
    messagingSenderId: '799670961061',
    projectId: 'temple-project-2d223',
    storageBucket: 'temple-project-2d223.firebasestorage.app',
    iosClientId: '799670961061-dbgulcqjfpn6r4h33a2vumne6jafnbhu.apps.googleusercontent.com',
    iosBundleId: 'com.example.temple',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs3a1OCrtUx8C_6ja3vzswjBQPTZwFmjc',
    appId: '1:799670961061:web:d58737df1f0ec6419bde4c',
    messagingSenderId: '799670961061',
    projectId: 'temple-project-2d223',
    authDomain: 'temple-project-2d223.firebaseapp.com',
    storageBucket: 'temple-project-2d223.firebasestorage.app',
    measurementId: 'G-7NVFL8SQ00',
  );

}