// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs3a1OCrtUx8C_6ja3vzswjBQPTZwFmjc',
    appId: '1:799670961061:web:8491086bfeefdd549bde4c',
    messagingSenderId: '799670961061',
    projectId: 'temple-project-2d223',
    authDomain: 'temple-project-2d223.firebaseapp.com',
    storageBucket: 'temple-project-2d223.firebasestorage.app',
    measurementId: 'G-DK6719MXY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1stOtrM-IPce0MOl3RHR6U5UxaxWmBkk',
    appId: '1:799670961061:android:047bcb70a6af7cbe9bde4c',
    messagingSenderId: '799670961061',
    projectId: 'temple-project-2d223',
    storageBucket: 'temple-project-2d223.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA26ZtYBQuI85WchwiwH2ixBmHnA4oepCQ',
    appId: '1:799670961061:ios:adf1436235cd92aa9bde4c',
    messagingSenderId: '799670961061',
    projectId: 'temple-project-2d223',
    storageBucket: 'temple-project-2d223.firebasestorage.app',
    androidClientId: '799670961061-0emuo3s98iiq4c2thkcb0gel16ppe6bs.apps.googleusercontent.com',
    iosClientId: '799670961061-1bm8ob0j0m7mikcjc2f2t39gi2o2m6u6.apps.googleusercontent.com',
    iosBundleId: 'com.example.templeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA26ZtYBQuI85WchwiwH2ixBmHnA4oepCQ',
    appId: '1:799670961061:ios:adf1436235cd92aa9bde4c',
    messagingSenderId: '799670961061',
    projectId: 'temple-project-2d223',
    storageBucket: 'temple-project-2d223.firebasestorage.app',
    androidClientId: '799670961061-0emuo3s98iiq4c2thkcb0gel16ppe6bs.apps.googleusercontent.com',
    iosClientId: '799670961061-1bm8ob0j0m7mikcjc2f2t39gi2o2m6u6.apps.googleusercontent.com',
    iosBundleId: 'com.example.templeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs3a1OCrtUx8C_6ja3vzswjBQPTZwFmjc',
    appId: '1:799670961061:web:b9a4f437d538b0b99bde4c',
    messagingSenderId: '799670961061',
    projectId: 'temple-project-2d223',
    authDomain: 'temple-project-2d223.firebaseapp.com',
    storageBucket: 'temple-project-2d223.firebasestorage.app',
    measurementId: 'G-HQ0H558V26',
  );
}
